// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJmXPaWeQk8JX1UjH5PSmzmCVwAYjhbRI',
    appId: '1:179634384652:web:b7f29d8e70e20cadd22329',
    messagingSenderId: '179634384652',
    projectId: 'stroller-fb9a8',
    authDomain: 'stroller-fb9a8.firebaseapp.com',
    storageBucket: 'stroller-fb9a8.appspot.com',
    measurementId: 'G-K4S4XCD5SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Fcz5lDfjk02wAkNi5LM9aRzPdwfYrW0',
    appId: '1:179634384652:android:35fa9df23ddd6c77d22329',
    messagingSenderId: '179634384652',
    projectId: 'stroller-fb9a8',
    storageBucket: 'stroller-fb9a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLPUaTtdRohni6gSHg4dHZAY0MrQlj1Ew',
    appId: '1:179634384652:ios:3b29af6aae9806dfd22329',
    messagingSenderId: '179634384652',
    projectId: 'stroller-fb9a8',
    storageBucket: 'stroller-fb9a8.appspot.com',
    iosClientId:
        '179634384652-t640k3064mt3h365enqinsrmp39o35nb.apps.googleusercontent.com',
    iosBundleId: 'com.iankwemboyasapplication.app',
  );
}
